# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fraud_detection.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




<<<<<<< Updated upstream
DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x66raud_detection.proto\x12\x05hello\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"!\n\rHelloResponse\x12\x10\n\x08greeting\x18\x01 \x01(\t2E\n\x0cHelloService\x12\x35\n\x08SayHello\x12\x13.hello.HelloRequest\x1a\x14.hello.HelloResponseb\x06proto3')
=======
DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x66raud_detection.proto\x12\x0f\x66raud_detection\"%\n\x04User\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontact\x18\x02 \x01(\t\"A\n\nCreditCard\x12\x0e\n\x06number\x18\x01 \x01(\t\x12\x16\n\x0e\x65xpirationDate\x18\x02 \x01(\t\x12\x0b\n\x03\x63vv\x18\x03 \x01(\t\"[\n\x0e\x42illingAddress\x12\x0e\n\x06street\x18\x01 \x01(\t\x12\x0c\n\x04\x63ity\x18\x02 \x01(\t\x12\r\n\x05state\x18\x03 \x01(\t\x12\x0f\n\x07\x63ountry\x18\x04 \x01(\t\x12\x0b\n\x03zip\x18\x05 \x01(\t\"\xa6\x01\n\x15\x46raudDetectionRequest\x12#\n\x04user\x18\x01 \x01(\x0b\x32\x15.fraud_detection.User\x12/\n\ncreditCard\x18\x02 \x01(\x0b\x32\x1b.fraud_detection.CreditCard\x12\x37\n\x0e\x62illingAddress\x18\x03 \x01(\x0b\x32\x1f.fraud_detection.BillingAddress\"?\n\x16\x46raudDetectionResponse\x12\x15\n\ris_fraudulent\x18\x01 \x01(\x08\x12\x0e\n\x06reason\x18\x02 \x01(\t2x\n\x15\x46raudDetectionService\x12_\n\nCheckFraud\x12&.fraud_detection.FraudDetectionRequest\x1a\'.fraud_detection.FraudDetectionResponse\"\x00\x62\x06proto3')
>>>>>>> Stashed changes

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fraud_detection_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
<<<<<<< Updated upstream
  _globals['_HELLOREQUEST']._serialized_start=32
  _globals['_HELLOREQUEST']._serialized_end=60
  _globals['_HELLORESPONSE']._serialized_start=62
  _globals['_HELLORESPONSE']._serialized_end=95
  _globals['_HELLOSERVICE']._serialized_start=97
  _globals['_HELLOSERVICE']._serialized_end=166
=======
  _globals['_USER']._serialized_start=42
  _globals['_USER']._serialized_end=79
  _globals['_CREDITCARD']._serialized_start=81
  _globals['_CREDITCARD']._serialized_end=146
  _globals['_BILLINGADDRESS']._serialized_start=148
  _globals['_BILLINGADDRESS']._serialized_end=239
  _globals['_FRAUDDETECTIONREQUEST']._serialized_start=242
  _globals['_FRAUDDETECTIONREQUEST']._serialized_end=408
  _globals['_FRAUDDETECTIONRESPONSE']._serialized_start=410
  _globals['_FRAUDDETECTIONRESPONSE']._serialized_end=473
  _globals['_FRAUDDETECTIONSERVICE']._serialized_start=475
  _globals['_FRAUDDETECTIONSERVICE']._serialized_end=595
>>>>>>> Stashed changes
# @@protoc_insertion_point(module_scope)
