# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: utils/pb/order_queue/order_queue.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&utils/pb/order_queue/order_queue.proto\x12\x0border_queue\"6\n\x11OrderQueueRequest\x12\x10\n\x08is_valid\x18\x01 \x01(\x08\x12\x0f\n\x07orderID\x18\x02 \x01(\t\":\n\x12OrderQueueResponse\x12\x13\n\x0bis_in_queue\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2f\n\x11OrderQueueService\x12Q\n\x0c\x45nqueueOrder\x12\x1e.order_queue.OrderQueueRequest\x1a\x1f.order_queue.OrderQueueResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'utils.pb.order_queue.order_queue_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ORDERQUEUEREQUEST']._serialized_start=55
  _globals['_ORDERQUEUEREQUEST']._serialized_end=109
  _globals['_ORDERQUEUERESPONSE']._serialized_start=111
  _globals['_ORDERQUEUERESPONSE']._serialized_end=169
  _globals['_ORDERQUEUESERVICE']._serialized_start=171
  _globals['_ORDERQUEUESERVICE']._serialized_end=273
# @@protoc_insertion_point(module_scope)
