# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: book_suggestions.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x62ook_suggestions.proto\x12\x08\x62ookshop\"0\n\x15\x42ookSuggestionRequest\x12\x17\n\x0fnum_suggestions\x18\x01 \x01(\x05\"%\n\x04\x42ook\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x02 \x01(\t\"=\n\x16\x42ookSuggestionResponse\x12#\n\x0bsuggestions\x18\x01 \x03(\x0b\x32\x0e.bookshop.Book2l\n\x0f\x42ookSuggestions\x12Y\n\x12GetBookSuggestions\x12\x1f.bookshop.BookSuggestionRequest\x1a .bookshop.BookSuggestionResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'book_suggestions_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_BOOKSUGGESTIONREQUEST']._serialized_start=36
  _globals['_BOOKSUGGESTIONREQUEST']._serialized_end=84
  _globals['_BOOK']._serialized_start=86
  _globals['_BOOK']._serialized_end=123
  _globals['_BOOKSUGGESTIONRESPONSE']._serialized_start=125
  _globals['_BOOKSUGGESTIONRESPONSE']._serialized_end=186
  _globals['_BOOKSUGGESTIONS']._serialized_start=188
  _globals['_BOOKSUGGESTIONS']._serialized_end=296
# @@protoc_insertion_point(module_scope)
