# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import book_suggestions_pb2 as book__suggestions__pb2


class BookSuggestionsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetBookSuggestions = channel.unary_unary(
                '/bookshop.BookSuggestions/GetBookSuggestions',
                request_serializer=book__suggestions__pb2.BookSuggestionRequest.SerializeToString,
                response_deserializer=book__suggestions__pb2.BookSuggestionResponse.FromString,
                )


class BookSuggestionsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetBookSuggestions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BookSuggestionsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetBookSuggestions': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBookSuggestions,
                    request_deserializer=book__suggestions__pb2.BookSuggestionRequest.FromString,
                    response_serializer=book__suggestions__pb2.BookSuggestionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'bookshop.BookSuggestions', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class BookSuggestions(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetBookSuggestions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bookshop.BookSuggestions/GetBookSuggestions',
            book__suggestions__pb2.BookSuggestionRequest.SerializeToString,
            book__suggestions__pb2.BookSuggestionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
